# Generated by Django 4.1 on 2023-01-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('aadhaar_file', models.FileField(upload_to='aadhaar/')),
            ],
        ),
    ]
