# Generated by Django 4.1 on 2023-01-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('joining_date', models.DateField()),
                ('last_working_date', models.DateTimeField(auto_now_add=True)),
                ('upload_document', models.FileField(upload_to='details/')),
            ],
        ),
    ]
