# Generated by Django 4.1.5 on 2023-02-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_timesheet_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='employee',
            field=models.TextField(max_length=50),
        ),
    ]
