# Generated by Django 4.1 on 2023-01-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='last_working_date',
            field=models.DateTimeField(),
        ),
    ]
